#!/bin/sh
# From QiuSimons

cd /overlay
rm -rf `ls | egrep -v '(upper|.fs_state)'`
cd /overlay/upper
rm -rf `ls | egrep -v '(etc|usr)'`
cd /overlay/upper/usr
rm -rf `ls | egrep -v '(share)'`
cd /overlay/upper/usr/share
rm -rf `ls`
cd /overlay/upper/etc
rm -rf `ls | egrep -v '(config|smartdns|bench.log|shadow|openclash|fucked)'`
cd /overlay/upper/etc/config
rm -rf `ls | egrep -v '(arpbind|autoreboot|ddns|firewall|network|openclash|sqm|dhcp)'`
sleep 5 && touch /etc/banner && reboot
